# Generated by Django 5.0.3 on 2024-05-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('founding_year', models.PositiveIntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/')),
                ('title', models.CharField(max_length=200)),
                ('pages', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('dimensions', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('cover_type', models.CharField(choices=[('Soft', 'Мека'), ('Hard', 'Тврда')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Biography', 'Biography'), ('Classic', 'Classic'), ('Drama', 'Drama'), ('History', 'History')], max_length=50)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstoreapp.publisher')),
            ],
        ),
    ]
